# Generated by Django 5.0.7 on 2025-02-03 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barangay', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('employee', 'Employee'), ('resident', 'Resident')], max_length=10),
        ),
    ]
